const categories = [
  { id: "product-copy", en: "Product copy", zh: "商品文案", intent: "Write product descriptions, bundles, FAQs, and benefit-led copy." },
  { id: "ad-creative", en: "Ad creative", zh: "广告素材", intent: "Create hooks, visual briefs, landing page angles, and paid social variants." },
  { id: "seo", en: "SEO", zh: "SEO 增长", intent: "Find keywords, briefs, internal links, and refresh opportunities." },
  { id: "email", en: "Email marketing", zh: "邮件营销", intent: "Build lifecycle campaigns, segmentation ideas, and abandoned cart flows." },
  { id: "support", en: "Customer support", zh: "客户支持", intent: "Automate support answers, returns workflows, and pre-sale Q&A." },
  { id: "image-video", en: "Image and video", zh: "图片视频", intent: "Produce product visuals, UGC concepts, reels, and ad assets." },
  { id: "research", en: "Research and analytics", zh: "调研分析", intent: "Analyze reviews, competitors, pricing, and conversion leaks." },
  { id: "automation", en: "Automation", zh: "自动化", intent: "Connect AI outputs with Shopify operations and repeatable workflows." }
];

const tools = [
  ["jasper","Jasper","product-copy","Paid","AI marketing copy workspace for product pages, campaigns, and brand voice.","Good for teams that need reusable tone controls across PDPs and ads.","商品页、广告文案和品牌语气管理，适合有固定调性的独立站团队。",["product copy","brand voice","ads"],true],
  ["copy-ai","Copy.ai","product-copy","Freemium","Go-to-market AI workspace for ecommerce copy, sales emails, and repeatable workflows.","Useful when operators want quick copy variants without building prompts from scratch.","适合快速生成商品卖点、邮件和广告角度，降低从零写提示词的成本。",["copy","workflows","sales"],true],
  ["writesonic","Writesonic","product-copy","Freemium","AI writer for product descriptions, SEO articles, landing pages, and ad copy.","A practical starter option for lean stores producing many SKU descriptions.","适合 SKU 多、需要批量生成描述和营销文案的卖家。",["descriptions","seo copy","landing pages"],true],
  ["anyword","Anyword","ad-creative","Paid","Predictive copy platform focused on performance messaging and paid media variants.","Good for testing hooks and claims before spending heavily on paid traffic.","偏广告转化文案，可用于测试不同卖点和投放角度。",["ad copy","prediction","testing"],true],
  ["hypotenuse-ai","Hypotenuse AI","product-copy","Paid","Ecommerce content generator for product descriptions, blogs, and catalog copy.","Strong fit for catalog-heavy Shopify stores that need consistent product copy.","适合目录型独立站，批量产出一致风格的商品描述。",["catalog","descriptions","blog"],true],
  ["copysmith","Copysmith","product-copy","Paid","Commerce-focused AI copy platform with catalog and campaign use cases.","Useful for merchants managing product listings across multiple channels.","适合多渠道商品文案管理，尤其是商品标题和短描述。",["catalog","marketplaces","copy"],true],
  ["chatgpt","ChatGPT","research","Freemium","General AI assistant for planning campaigns, rewriting copy, and analyzing customer feedback.","Best as a flexible thinking partner when paired with clear ecommerce workflows.","通用 AI 助手，适合做选品分析、评论归纳、文案改写和运营规划。",["research","copy","analysis"],false],
  ["claude","Claude","research","Freemium","Long-context AI assistant for research, customer review analysis, and detailed playbooks.","Useful for summarizing long exports, support logs, and competitor pages.","长文本处理能力强，适合分析评论、客服记录和竞品页面。",["analysis","long context","strategy"],false],
  ["notion-ai","Notion AI","automation","Paid","AI writing and knowledge base features inside Notion workspaces.","Good for documenting repeatable Shopify operating procedures and content calendars.","适合把运营 SOP、内容日历和复盘沉淀到团队知识库。",["sop","planning","knowledge base"],true],
  ["perplexity","Perplexity","research","Freemium","AI answer engine for market research, source discovery, and competitor scanning.","Useful for quick research before writing buying guides or comparison pages.","适合做市场资料搜集、竞品调研和内容选题验证。",["research","sources","competitors"],false],
  ["semrush","Semrush","seo","Paid","SEO suite for keyword research, competitive analysis, content planning, and rank tracking.","Best for stores serious about organic traffic and content operations.","SEO 全家桶，适合把自然流量当长期增长渠道的独立站。",["keyword research","rank tracking","content"],true],
  ["ahrefs","Ahrefs","seo","Paid","SEO research platform for keywords, backlinks, competitor pages, and content gaps.","Strong for finding long-tail ecommerce keywords and link opportunities.","适合挖长尾词、竞品页面和外链机会。",["seo","backlinks","keywords"],true],
  ["surfer-seo","Surfer SEO","seo","Paid","Content optimization tool that suggests structure, terms, and on-page improvements.","Useful for turning product guides into more competitive search pages.","适合优化商品指南、博客和类目内容的页面结构。",["content optimization","briefs","seo"],true],
  ["frase","Frase","seo","Paid","AI SEO content brief and optimization platform for search-driven articles.","Good for repeatable article briefs and FAQ extraction.","适合生成 SEO 内容大纲、FAQ 和文章优化建议。",["briefs","faq","seo"],true],
  ["clearscope","Clearscope","seo","Paid","Content optimization software for high-quality SEO briefs and topical coverage.","Best for teams willing to invest in fewer, stronger evergreen pages.","适合少量高质量常青内容，不适合只追求低成本批量产出。",["seo briefs","content quality","optimization"],true],
  ["klaviyo","Klaviyo","email","Paid","Email and SMS marketing platform with AI-assisted segmentation and ecommerce automations.","One of the strongest fits for Shopify lifecycle marketing.","Shopify 邮件营销强势工具，适合弃购、复购、会员分层和自动化流程。",["email","sms","segmentation"],true],
  ["omnisend","Omnisend","email","Paid","Email and SMS platform for ecommerce automation, campaigns, and popups.","A pragmatic option for lean stores that want email, SMS, and forms together.","适合希望把邮件、短信和弹窗表单放在一个系统里的中小卖家。",["email","sms","forms"],true],
  ["mailchimp","Mailchimp","email","Freemium","Email marketing platform with AI content and basic ecommerce automations.","Better for simple newsletters than complex Shopify lifecycle flows.","适合轻量邮件和内容型 newsletter，复杂电商自动化略弱。",["newsletter","email","automation"],true],
  ["privy","Privy","email","Paid","Shopify-focused popups, email, and SMS capture for growing ecommerce stores.","Good for list growth offers, exit intent, and first-purchase incentives.","适合独立站收集邮箱、首单优惠和弹窗转化。",["popups","email capture","sms"],true],
  ["yotpo-email","Yotpo Email","email","Paid","Ecommerce email and SMS platform connected with reviews and loyalty products.","Good when reviews, loyalty, SMS, and email need one ecosystem.","适合评论、会员、短信和邮件想统一管理的品牌。",["email","sms","reviews"],true],
  ["gorgias","Gorgias","support","Paid","Ecommerce helpdesk with automation, macros, and AI support features.","Strong Shopify fit for support teams handling order, return, and product questions.","Shopify 客服台标杆之一，适合订单、退换货和售前问题自动化。",["helpdesk","shopify","automation"],true],
  ["tidio","Tidio","support","Freemium","Live chat and AI chatbot platform for ecommerce stores.","Good starter chatbot for pre-sale questions and lead capture.","适合中小独立站做在线聊天、售前问答和线索收集。",["chatbot","live chat","lead capture"],true],
  ["zendesk-ai","Zendesk AI","support","Paid","Enterprise-grade support platform with AI routing, summarization, and agent assistance.","Better for larger support teams than early solo operators.","适合客服规模较大的团队，早期独立站可能偏重。",["support","routing","agent assist"],true],
  ["intercom","Intercom","support","Paid","AI customer service and messaging platform for support and onboarding.","Useful for stores with higher-ticket products and consultative pre-sale questions.","适合高客单、需要售前咨询和自动客服结合的店铺。",["support","messaging","ai agent"],true],
  ["re-amaze","Re:amaze","support","Paid","Customer messaging and helpdesk built for ecommerce teams.","A compact Shopify-friendly support hub with chat, email, and automation.","面向电商团队的客服工具，适合整合聊天、邮件和自动回复。",["helpdesk","chat","ecommerce"],true],
  ["canva","Canva","image-video","Freemium","Design platform with AI image, video, copy, and brand kit tools.","The fastest default for non-designers making ads, banners, and social assets.","非设计师友好，适合广告图、社媒图、活动横幅和品牌模板。",["design","ads","social"],true],
  ["adcreative-ai","AdCreative.ai","ad-creative","Paid","AI platform for generating conversion-oriented ad creatives and copy variants.","Useful when paid social teams need many visual concepts quickly.","适合快速生成大量广告图概念和投放版本。",["ad creative","variants","paid social"],true],
  ["pencil","Pencil","ad-creative","Paid","AI creative generation and testing platform for ecommerce advertising.","Good for brands that want structured ad testing and learning loops.","适合想系统测试广告素材、沉淀投放学习的品牌。",["creative testing","ads","learning"],true],
  ["predis-ai","Predis.ai","ad-creative","Paid","AI social media and ad creative generator for posts, captions, and videos.","Useful for small teams that need social content calendars and variants.","适合小团队生成社媒内容日历、短视频和广告文案。",["social","ads","calendar"],true],
  ["midjourney","Midjourney","image-video","Paid","AI image generation tool for moodboards, product concept visuals, and campaign art.","Best for creative direction, not final factual product photography.","适合做视觉方向和场景概念，不适合替代真实商品图。",["image generation","moodboard","creative"],false],
  ["runway","Runway","image-video","Paid","AI video editing and generation suite for short-form content and creative experiments.","Useful for testing video hooks and motion concepts before production.","适合短视频创意、动态素材和视频钩子实验。",["video","editing","generation"],true],
  ["descript","Descript","image-video","Paid","AI audio and video editor for demos, UGC-style videos, and tutorials.","Good for repurposing product walkthroughs into clips and ads.","适合把产品演示、口播和教程剪成短内容。",["video editing","ugc","audio"],true],
  ["capcut","CapCut","image-video","Freemium","Video editor with AI captions, templates, and short-form workflows.","Good low-cost option for TikTok, Reels, and Shorts production.","低成本短视频工具，适合字幕、模板和快速剪辑。",["short video","captions","templates"],false],
  ["invideo","InVideo","image-video","Paid","AI video creation platform for ads, explainers, and social videos.","Useful for creating scripted ecommerce videos without a full editing team.","适合用脚本生成电商广告、讲解视频和社媒视频。",["video ads","script to video","social"],true],
  ["beautiful-ai","Beautiful.ai","image-video","Paid","AI presentation design tool for investor decks, wholesale pitches, and internal reports.","Useful for Shopify brands pitching retail, wholesale, or partners.","适合品牌做招商、批发合作和内部复盘演示。",["presentations","decks","reporting"],true],
  ["hotjar","Hotjar","research","Paid","Behavior analytics for heatmaps, recordings, surveys, and conversion insight.","Use it to find where AI-written pages still confuse shoppers.","适合看热图、录屏和问卷，找出页面转化卡点。",["analytics","heatmaps","surveys"],true],
  ["microsoft-clarity","Microsoft Clarity","research","Free","Free behavior analytics with heatmaps and session recordings.","A good first analytics layer for finding checkout and PDP friction.","免费行为分析，适合早期观察商品页和结账流程问题。",["heatmaps","recordings","free"],false],
  ["triple-whale","Triple Whale","research","Paid","Ecommerce analytics and attribution platform with AI insights for DTC brands.","Useful once ad spend and channel complexity justify deeper attribution.","适合广告渠道复杂、需要归因和利润视角的 DTC 品牌。",["attribution","analytics","dtc"],true],
  ["northbeam","Northbeam","research","Paid","Marketing measurement platform for ecommerce media mix and attribution.","Better for scaling brands with meaningful paid spend.","适合投放规模较大的品牌做媒体归因和预算判断。",["measurement","attribution","media"],true],
  ["peel-insights","Peel Insights","research","Paid","Ecommerce analytics platform for cohorts, retention, and customer insights.","Useful for understanding retention, repeat purchase, and product performance.","适合分析留存、复购、客群和产品表现。",["cohorts","retention","analytics"],true],
  ["zapier","Zapier","automation","Paid","No-code automation platform for connecting Shopify, AI tools, sheets, and CRMs.","Good for moving AI outputs into repeatable operations.","适合把 Shopify、表格、AI 工具和邮件系统串成自动流程。",["automation","integrations","ops"],true],
  ["make","Make","automation","Paid","Visual automation platform for multi-step workflows and ecommerce operations.","Useful when workflows need branching, enrichment, or scheduled updates.","适合多步骤自动化，比如评论分析、库存提醒和内容排期。",["automation","workflow","integrations"],true],
  ["airtable","Airtable","automation","Paid","Flexible database for content calendars, tool databases, and ecommerce ops trackers.","Good MVP database before custom software is needed.","适合作为内容库、工具库和运营追踪表。",["database","content ops","tracking"],true],
  ["shopify-flow","Shopify Flow","automation","Included","Shopify automation builder for order, customer, and inventory workflows.","Best native option for simple Shopify operational automations.","Shopify 原生自动化，适合订单、客户和库存规则。",["shopify","automation","ops"],false],
  ["mechanic","Mechanic","automation","Paid","Shopify automation app for custom operational tasks and scripts.","Useful for stores that need deeper Shopify automations without a full custom app.","适合需要更灵活 Shopify 自动化但不想开发完整应用的团队。",["shopify app","automation","custom tasks"],true],
  ["okendo","Okendo","support","Paid","Customer reviews and surveys platform with ecommerce insights.","Useful for mining customer language and feeding AI copy prompts.","适合收集评价和问卷，再反哺商品文案与广告卖点。",["reviews","surveys","voice of customer"],true],
  ["yotpo-reviews","Yotpo Reviews","support","Paid","Review platform for ecommerce brands with UGC and retention ecosystem options.","Good for social proof and review-driven content insights.","适合评论、UGC 和社会证明，也能辅助提炼卖点。",["reviews","ugc","social proof"],true],
  ["loox","Loox","support","Paid","Photo and video review app for Shopify merchants.","Strong for visual social proof, especially fashion, beauty, and home goods.","适合图片/视频评论，尤其美妆、服饰、家居等视觉品类。",["photo reviews","ugc","shopify"],true],
  ["judge-me","Judge.me","support","Freemium","Affordable Shopify review app with review collection and display features.","Good starter review app for budget-conscious Shopify stores.","性价比高，适合早期独立站建立评价体系。",["reviews","shopify","social proof"],true],
  ["typefully","Typefully","ad-creative","Paid","Social writing and scheduling tool with AI assistance for founder-led content.","Useful for founders sharing build-in-public and ecommerce lessons.","适合创始人或品牌主做社媒内容和长期个人 IP。",["social writing","scheduling","founder"],true],
  ["buffer","Buffer","ad-creative","Freemium","Social scheduling platform with AI assistance for captions and repurposing.","Practical for lightweight social distribution across channels.","适合轻量社媒排程和文案改写。",["social scheduling","captions","distribution"],true]
].map(([slug,name,category,pricing,summary,bestFor,zhSummary,tags,affiliate]) => ({ slug,name,category,pricing,summary,bestFor,zhSummary,tags,affiliate }));

const tutorialsEn = [
  ["write-shopify-product-descriptions-ai","How to write Shopify product descriptions with AI","product-copy","Use review mining, benefit mapping, and brand voice prompts to produce product pages that sell instead of sounding generic."],
  ["generate-facebook-ad-creatives-shopify","How to generate Facebook ad creatives for a Shopify store","ad-creative","Turn product benefits into hook angles, image briefs, and variant testing plans for Meta ads."],
  ["shopify-seo-ai-workflow","AI SEO workflow for Shopify collection and product pages","seo","A repeatable process for keyword mapping, title rewrites, FAQ blocks, and internal links."],
  ["abandoned-cart-email-ai","Write abandoned cart emails with AI for Shopify","email","Build a three-message cart recovery flow with urgency, objections, and product-specific proof."],
  ["ai-chatbot-pre-sale-questions","Use an AI chatbot to answer pre-sale Shopify questions","support","Create a support knowledge base from policies, sizing, shipping, and product questions."],
  ["product-photo-ai-briefs","Create AI image briefs for ecommerce product photos","image-video","Write useful creative briefs for lifestyle shots, backgrounds, and seasonal campaigns."],
  ["analyze-customer-reviews-ai","Analyze Shopify customer reviews with AI","research","Extract objections, desired outcomes, and customer language from reviews and support logs."],
  ["weekly-ai-content-calendar","Build a weekly AI content calendar for a Shopify brand","automation","Plan email, blog, and social assets from one promotional theme."],
  ["compare-ai-email-tools","Compare AI email tools for ecommerce lifecycle marketing","email","Decide when Klaviyo, Omnisend, or Mailchimp fits your store stage."],
  ["ai-landing-page-angle-test","Use AI to test landing page angles before buying traffic","ad-creative","Create benefit-led page variants and evaluate them with customer objections."],
  ["shopify-faq-ai","Create Shopify FAQ sections with AI","product-copy","Turn policy and product information into search-friendly FAQ content."],
  ["ai-for-seasonal-campaigns","Plan seasonal ecommerce campaigns with AI","ad-creative","Build Black Friday, holiday, and launch campaigns without starting from a blank page."],
  ["shopify-blog-briefs-ai","Write Shopify blog briefs with AI","seo","Produce briefs that target buyer intent, not empty top-of-funnel traffic."],
  ["support-macros-ai","Create support macros with AI for returns and shipping","support","Standardize replies while keeping human review for sensitive cases."],
  ["ugc-video-scripts-ai","Generate UGC-style video scripts with AI","image-video","Create creator briefs, hooks, and scene-by-scene scripts for short videos."],
  ["competitor-page-analysis-ai","Analyze competitor product pages with AI","research","Compare positioning, offer structure, proof, FAQs, and visual hierarchy."],
  ["shopify-flow-ai-ops","Use AI ideas with Shopify Flow automations","automation","Turn repeated operational tasks into simple Shopify Flow rules."],
  ["email-segmentation-ai","Use AI to brainstorm ecommerce email segments","email","Find segments based on purchase behavior, browsing intent, and product affinity."],
  ["seo-refresh-ai","Refresh old Shopify SEO pages with AI","seo","Audit stale pages and improve headings, internal links, FAQ, and comparison sections."],
  ["affiliate-disclosure-ecommerce-ai-site","Write affiliate disclosures for an AI tools site","research","Keep monetization transparent while preserving trust and editorial usefulness."]
].map(([slug,title,category,summary]) => ({ lang:"en",slug,title,category,summary }));

const tutorialsZh = [
  ["ai-xie-shopify-shangpinmiaoshu","用 AI 写 Shopify 商品描述的实战流程","product-copy","从买家评论、卖点拆解、品牌语气到页面结构，避免生成一眼 AI 的空话。"],
  ["ai-shengcheng-facebook-guanggao","用 AI 生成独立站 Facebook 广告素材","ad-creative","把商品利益点变成钩子、画面 brief 和多版本测试计划。"],
  ["shopify-seo-ai-liucheng","Shopify SEO 的 AI 工作流","seo","用 AI 做关键词映射、标题优化、FAQ 和内链建议。"],
  ["ai-qigou-youjian","用 AI 写 Shopify 弃购邮件","email","构建三封邮件流程：提醒、异议处理、信任证明。"],
  ["ai-kefu-shouqianwenda","用 AI 客服回答独立站售前问题","support","把尺码、物流、退换货和商品 FAQ 整理成客服知识库。"],
  ["ai-shangpintu-brief","用 AI 写电商商品图拍摄 brief","image-video","生成生活方式图、季节活动图和广告图的创意要求。"],
  ["ai-fenxi-kehu-pinglun","用 AI 分析独立站客户评论","research","提炼真实语言、购买动机、常见异议和广告卖点。"],
  ["ai-neirong-rili","为 Shopify 品牌建立一周 AI 内容日历","automation","把一个促销主题拆成邮件、博客、短视频和社媒内容。"],
  ["ai-youjian-gongju-duibi","电商 AI 邮件工具怎么选","email","比较 Klaviyo、Omnisend、Mailchimp 的适用阶段。"],
  ["ai-luodiyexiaoduiceshi","用 AI 测试独立站落地页角度","ad-creative","围绕利益点、受众和购买异议生成页面版本。"],
  ["shopify-faq-ai","用 AI 生成 Shopify FAQ 区块","product-copy","把政策和商品信息变成对 SEO 与转化都有帮助的 FAQ。"],
  ["ai-jijiexing-yingxiao","用 AI 规划季节性电商活动","ad-creative","适用于黑五、圣诞、上新和清仓活动。"],
  ["shopify-boke-dagang-ai","用 AI 写 Shopify 博客 SEO 大纲","seo","聚焦买家意图，不写没有转化价值的泛流量文章。"],
  ["ai-kefu-huashu","用 AI 生成客服宏回复","support","统一物流、退换货、尺码咨询等高频问题的回复。"],
  ["ai-ugc-duanshipin-jiaoben","用 AI 生成 UGC 短视频脚本","image-video","输出创作者 brief、前三秒钩子和分镜脚本。"],
  ["ai-jingpin-yemian-fenxi","用 AI 分析竞品商品页","research","比较定位、报价、信任元素、FAQ 和页面层级。"],
  ["shopify-flow-ai-zidonghua","结合 AI 思路使用 Shopify Flow","automation","把重复运营动作转成简单自动化规则。"],
  ["ai-youjian-fenceng","用 AI 设计电商邮件分层","email","按购买行为、浏览意图和品类偏好拆分用户。"],
  ["ai-shuaxin-seo-yemian","用 AI 刷新旧的 Shopify SEO 页面","seo","优化旧文章的标题、内链、FAQ 和对比模块。"],
  ["ai-daohang-lianmeng-pilu","AI 工具站如何写联盟披露","research","既透明告知变现方式，也保留内容可信度。"]
].map(([slug,title,category,summary]) => ({ lang:"zh",slug,title,category,summary }));

const comparisons = [
  ["best-ai-product-description-tools-shopify","Best AI product description tools for Shopify","product-copy",["jasper","copy-ai","hypotenuse-ai","writesonic","copysmith"]],
  ["best-ai-ad-creative-tools-shopify","Best AI ad creative tools for Shopify","ad-creative",["adcreative-ai","pencil","predis-ai","canva","anyword"]],
  ["best-shopify-ai-seo-tools","Best AI SEO tools for Shopify","seo",["semrush","ahrefs","surfer-seo","frase","clearscope"]],
  ["klaviyo-vs-omnisend-ai","Klaviyo AI vs Omnisend AI for Shopify","email",["klaviyo","omnisend","mailchimp","privy","yotpo-email"]],
  ["best-ai-chatbots-shopify","Best AI chatbots and helpdesks for Shopify","support",["gorgias","tidio","intercom","re-amaze","zendesk-ai"]],
  ["best-ai-image-video-tools-ecommerce","Best AI image and video tools for ecommerce","image-video",["canva","runway","descript","capcut","invideo"]],
  ["best-ai-research-tools-dtc","Best AI research tools for DTC ecommerce teams","research",["chatgpt","claude","perplexity","hotjar","microsoft-clarity"]],
  ["best-shopify-automation-ai-stack","Best automation stack for AI-assisted Shopify operations","automation",["zapier","make","airtable","shopify-flow","mechanic"]],
  ["best-review-tools-ai-copy-mining","Best review tools for AI copy mining","support",["okendo","yotpo-reviews","loox","judge-me","gorgias"]],
  ["lean-shopify-ai-stack-under-200","Lean Shopify AI stack under $200/month","automation",["chatgpt","canva","omnisend","tidio","microsoft-clarity"]]
].map(([slug,title,category,toolSlugs]) => ({ slug,title,category,toolSlugs }));

const matcherUseCases = [
  { id:"descriptions", en:"Improve product descriptions", zh:"优化商品描述", categories:["product-copy","research"], recommended:["jasper","copy-ai","hypotenuse-ai","chatgpt","okendo"] },
  { id:"ads", en:"Create paid ad concepts", zh:"生成广告素材", categories:["ad-creative","image-video"], recommended:["adcreative-ai","pencil","canva","predis-ai","anyword"] },
  { id:"seo", en:"Grow Shopify SEO", zh:"提升 SEO 流量", categories:["seo","research"], recommended:["semrush","ahrefs","surfer-seo","frase","perplexity"] },
  { id:"email", en:"Build email flows", zh:"搭建邮件自动化", categories:["email","automation"], recommended:["klaviyo","omnisend","privy","mailchimp","copy-ai"] },
  { id:"support", en:"Automate customer support", zh:"自动化客服", categories:["support","automation"], recommended:["gorgias","tidio","re-amaze","intercom","shopify-flow"] },
  { id:"video", en:"Make short videos", zh:"制作短视频", categories:["image-video","ad-creative"], recommended:["capcut","runway","descript","invideo","canva"] }
];

module.exports = { categories, tools, tutorials: [...tutorialsEn, ...tutorialsZh], comparisons, matcherUseCases };
